baseURL = "https://bwtake.github.io/fbl-site/"
languageCode = "ja-jp"
title = "未来サイバー生命体研究所 (Future BioCybernetics Lab)"
theme = "ananke"
canonifyURLs = true

[menu]
  [[menu.main]]
    name = "所長紹介"
    pageRef = "bwtake/_index.md"
    weight = 10

  [[menu.main]]
    name = "CGTA紹介"
    pageRef = "cgta/_index.md"
    weight = 20

  [[menu.main]]
    name = "観測ノート"
    pageRef = "posts/_index.md"
    weight = 30

  [[menu.main]]
    name = "FBL"
    pageRef = "fbl-central-question/_index.md"
    weight = 5

[params]
  mainSections = ["posts"]
  recentPostsLimit = 3
  custom_css = ["custom.css"]
  googleAnalytics = "G-XTDDG90VL1"

[outputs]
home     = ["HTML","RSS"]
section  = ["HTML","RSS"]
taxonomy = ["HTML","RSS"]
term     = ["HTML","RSS"]

# すでにある baseURL, params, [outputs] 等の下あたりに追加
[module]
  [module.hugoVersion]
    min = "0.128.0"     # 使うHugoの最小バージョン要件
    # extended = true   # 拡張版が必須なら付ける（AnankeはSCSSありなので拡張版推奨）
